[project]
name = "geoguessr-scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "selenium",
    "genanki",
    "beautifulsoup4",
    "ruff",
    "requests",
    "tqdm",
    "basedpyright",
    "playwright",
    "pillow",
    "trio",
    "google-genai",
    "streetview",
    "gooey",
]

[tool.basedpyright]
include = ["learnable_meta_anki"]
defineConstant = { DEBUG = true }
reportAny = false
reportExplicitAny = false

executionEnvironments = [
  { root = "src/web", pythonVersion = "3.5", pythonPlatform = "Windows", extraPaths = [ "src/service_libs" ], reportMissingImports = "warning" },
  { root = "src/sdk", pythonVersion = "3.0", extraPaths = [ "src/backend" ] },
  { root = "src/tests", reportPrivateUsage = false, extraPaths = ["src/tests/e2e", "src/sdk" ]},
  { root = "src" }
]

[tool.ruff]
line-length = 120
